### ISSUE TITLE
Optional custom color for tag

### ISSUE THREAD

**Issue by RiccardoRaccuglia** [agebase/projects-for-trello#17]
I apologize, It is a request of a new feature and not a issue.
I wish I set custom tag on trello cards.
I am using trello labes for priority/topic

I often need to set up special tags:
It is the idea:
![needs](https://user-images.githubusercontent.com/23580119/27001569-902f2a6c-4dcd-11e7-89a6-ab8aba9fb6d7.PNG)

Thanks

**Comment by danlister** [comment]
#20 fixes this issue.
